# Generated by Django 6.0.2 on 2026-03-02 10:18

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='core_compan_scrape__3d1e53_idx',
            old_name='core_compan_scrape__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='core_compan_industr_78413a_idx',
            old_name='core_compan_industr_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='core_compan_country_8d6c23_idx',
            old_name='core_compan_country_g7h8i9_idx',
        ),
        migrations.AlterField(
            model_name='companyembedding',
            name='vector',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
