# Generated by Django 6.0.2 on 2026-03-02 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_change_embedding_dimensions_to_768'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vat_number', models.CharField(blank=True, help_text='Partita IVA', max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='What the company does', null=True)),
                ('services', models.JSONField(blank=True, default=list, help_text='List of services/products')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'company properties',
            },
        ),
    ]
