# Generated by Django 6.0.2 on 2026-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_company_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproperties',
            name='extracted_at',
            field=models.DateTimeField(blank=True, help_text='When properties were extracted', null=True),
        ),
        migrations.AddField(
            model_name='companyproperties',
            name='model_name',
            field=models.CharField(blank=True, help_text='Ollama model used for extraction', max_length=100, null=True),
        ),
    ]
